### ISSUE TITLE
Could you add some Motivation to the main readme?

### ISSUE THREAD

**Issue by shevegen** [ChrisRx/dungeonfs#1]
Hello there,

Do you think it may be possible to add some motivation to the main readme as to why the project was started? It may perhaps be of interest to some people who may find it.

Thanks for reading!

**Comment by ChrisRx** [comment]
This is good suggestion and I will certainly do so.  I wanted to spiff up the README in general anyway (like mention all the things missing from the scripting mini-language, better getting started, etc), and this would be a good addition.
