### ISSUE TITLE
build err

### ISSUE THREAD

**Issue by konfou** [ChrisRx/dungeonfs#3]
Using
```shell
make deps
make
```
results in the following error
```shell
Building ...
cmd/dungeonfs/main.go:8:2: cannot find package "github.com/ChrisRx/dungeonfs/cmd/dungeonfs/command" in any of:
	/usr/lib/go/src/github.com/ChrisRx/dungeonfs/cmd/dungeonfs/command (from $GOROOT)
	/home/konstantinos/go/src/github.com/ChrisRx/dungeonfs/cmd/dungeonfs/command (from $GOPATH)
make: *** [Makefile:7: build] Error 1
```
probably because of the usage of remote import path as using
```shell
go get -u github.com/ChrisRx/dungeonfs
```
successfully builds a binary at `$GOPATH/bin` which though doesn't work.

**Comment by ChrisRx** [comment]
My build instructions are wrong, and I also left a main package in the project root that should probably go away (it is that empty binary that it is probably getting loaded when you use `go get`).  See if this works for you:

```
go get -u github.com/ChrisRx/dungeonfs...
```

Which should also download the example files into your `$GOPATH/src/github.com/ChrisRx/dungeonfs/examples`.  If it works let me know and I can correct it in the README.md!

**Comment by brannondorsey** [comment]
@ChrisRx I had the same issue as the OP and your solution worked. Thanks!
